### ISSUE TITLE
Can share the NYUDepth model?

### ISSUE THREAD

**Issue by nian-liu** [danxuhk/StructuredAttentionDepthEstimation#1]
Hi Dan,

I want to use your code to test on the NYUDepth v2 dataset, can you share the model or the depth maps? Thank you.

**Comment by danxuhk** [comment]
Hi, the training and testing model on NYUD-V2 will be released soon ...

**Comment by hypercost** [comment]
@danxuhk Will the code of PAD-Net be available?
