### ISSUE TITLE
Troubles in testing using a trained model

### ISSUE THREAD

**Issue by callme739** [danxuhk/StructuredAttentionDepthEstimation#3]
hi

When testing using the trained model, I confirmed the following error.
I appreciate it if you can help me.

```
F0923 20:56:26.518996 20742 net.cpp:757] Cannot copy param 0 weights from layer 'atten_f1_mf1'; shape mismatch.  Source param shape is 1 1024 3 3 (9216); target param shape is 512 1024 3 3 (4718592). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.
```

**Comment by danxuhk** [comment]
@callme739 Do you use our trained model and the testing script for testing? What batch size do you use in testing?

**Comment by callme739** [comment]
I used a model that I had retrained based on train.py, and I used your test.sh for testing.
Batch size is still the default.prototxt has not changed anything.

**Comment by danxuhk** [comment]
@callme739 Our test.sh uses the test.prototxt, in which the testing batch_size is set to 1, not the batch_size used in the training prototxt. You may check with this.

**Comment by callme739** [comment]
I changed batch_size in test.prototxt but it did not improve. Specifically, how is it appropriate to specify batch_size?

**Comment by danxuhk** [comment]
@callme739 Could you post here your data layer in your training prototxt and testing prototxt?

**Comment by callme739** [comment]
I could correctly specify and could fix the bug.

thanks!

**Comment by junfengcao** [comment]
I also met the same  question, and I found that the  atten_f1_mf1 layer's num_output is 1 and tiled to 512 in training model, but the dimension of atten_f1_mf1 layer's num_output is 512. Have you solved this error?
