### ISSUE TITLE
Confusion about the term

### ISSUE THREAD

**Issue by abeyang00** [danxuhk/StructuredAttentionDepthEstimation#6]
<img width="410" alt="screen shot 2018-12-26 at 5 11 10 pm" src="https://user-images.githubusercontent.com/36392866/50438461-5d9b0a00-0931-11e9-9b4d-1521669eb1b5.png">

What is K exactly? How can the dimension of K be C_s x C_S? Doesn't the whole term reduce down to a constant? 

Thank you

**Comment by junfengcao** [comment]
Hi，using this code，have you successfully reproduced   the performance in the paper？

**Comment by danxuhk** [comment]
The model we released produced better accuracy than the results reported in our paper ...

**Comment by junfengcao** [comment]
Ok，thanks for your release model. Because I am a new learner in deep learning，so I still can not  train a caffemodel which is the same as  "SAN_deploy.caffemodel" using the train_SAN.prototxt and  solver,prototxt. So could you share me some training trick for your model ? Thanks again...
