### ISSUE TITLE
kitti depth ground_truth generator

### ISSUE THREAD

**Issue by FrancsXiang** [danxuhk/StructuredAttentionDepthEstimation#9]
I am a graduate student from China,XTU.I am puzzled about the method generating kitti ground_truth.I use the kitti raw lidar data,but the depth_maps are sparse.
I will appreciate it if you have any time to deal with it.

**Comment by danxuhk** [comment]
In the training, we use the sparse gt depth data. The invalid points are ignored in the loss.

**Comment by FrancsXiang** [comment]
It is same like what I do now,thanks a lot.
